/* Portfolio content. Text supports **bold** and `code`. Avoid ASCII single quotes inside strings.
   Each project reads as problem → approach → result; keep numbers to the few that prove the result. */
window.PORTFOLIO = {
  profile: {
    name: '고상혁',
    nameEn: 'Sanghyuk Ko',
    email: '90sangko@naver.com',
    github: 'https://github.com/sanghyuk-ko',
  },

  hero: {
    lines: ['PROOF', 'OVER PROMISE'],
    linesMobile: ['PROOF', 'OVER', 'PROMISE'],
    evidence: [
      '_update() → allowlist.isAllowed(to) || revert',
      'approvals >= required → transition',
      'amount && docHash must match → record',
      'verifyMessage(msg, sig) == addr → delete nonce',
      'a name alone is not evidence',
      'list incomplete || stale → blocked',
      'accept → job folder → result file',
      'measure → prove → migrate',
    ],
  },

  marquee: ['RWA', 'ERC-1155', 'KYC Allowlist', 'Sanctions Screening', 'Solidity', 'Foundry', 'Spring Boot', 'TypeScript'],

  projects: [
    /* ------------------------------------------------------------------ */
    {
      id: 'art-abs',
      featured: true,
      span: 7,
      visual: 'tranche',
      title: 'Art-ABS 트랜치 컨트랙트',
      category: 'RWA · Smart Contract',
      org: '한화미래금융공모전',
      period: '2026.02',
      role: '컨트랙트 설계 · 구현',
      team: '3인 팀',
      stack: ['Solidity', 'Foundry', 'OpenZeppelin', 'ERC-1155'],
      oneLiner: '미술품 ABS에서 분쟁이 생기는 양도 · 권리 · 정산을 스마트 컨트랙트 규칙으로 옮겼습니다.',
      summary: '토큰을 발행하는 것보다, 발행한 뒤 **누가 보유하고, 누가 결정하고, 어떻게 나누는지**를 코드로 강제하는 데 집중한 RWA 컨트랙트입니다.',
      snapshot: {
        problem: '토큰화된 자산은 발행 뒤가 문제입니다. 자격 없는 지갑으로의 양도, 한 사람의 단독 결정, 검증할 수 없는 정산이 분쟁을 만듭니다.',
        approach: '세 분쟁 지점을 컨트랙트 하나씩의 책임으로 나누고, 외부 데이터를 믿는 대신 **합의와 문서 해시로 대조**하게 했습니다.',
        result: '양도 · 권리 · 정산이 모두 온체인 규칙으로 통제되는 MVP를 만들어 **한화미래금융공모전 2라운드**에 진출했습니다.',
      },
      metrics: [
        { value: '3', unit: '곳', label: '규칙으로 옮긴 분쟁 지점' },
        { value: '2', unit: 'of 3', label: '정산 기록에 필요한 합의', count: false },
      ],
      decisions: [
        { title: '양도 — 옮겨질 때마다 자격을 확인합니다', body: '민팅 · 전송 · 소각이 모두 지나가는 `_update` 훅에서 양쪽 지갑의 KYC 허용목록을 검사해, 발행 뒤 2차 전송까지 막았습니다.' },
        { title: '권리 — 한 사람이 상태를 바꿀 수 없습니다', body: '매각 같은 상태 전이는 지정된 서명자들의 승인이 기준 수에 닿고 근거 문서 해시가 함께 제출돼야만 일어납니다.' },
        { title: '정산 — 믿지 않고 대조합니다', body: '오라클 3명 중 2명이 같은 금액과 같은 문서 해시를 내야 수입이 기록되고, 수익은 Senior → Mezzanine → Equity 순서로 나뉩니다.' },
      ],
      flow: [
        { k: '01', b: 'AllowlistRegistry', s: 'KYC 통과 지갑' },
        { k: '02', b: 'TrancheToken', s: '전송마다 자격 검사' },
        { k: '03', b: 'DealStateMachine', s: '서명자 합의로 전이', key: true },
        { k: '04', b: 'Oracle 2-of-3', s: '금액 + 문서 해시' },
        { k: '05', b: 'WaterfallSettlement', s: '우선순위 분배' },
      ],
      code: [
        {
          file: 'src/TrancheToken.sol',
          caption: '민팅 · 전송 · 소각이 모두 지나가는 훅 하나에서 양쪽 지갑을 검사합니다.',
          snippet: [
            'function _update(',
            '    address from,',
            '    address to,',
            '    uint256[] memory ids,',
            '    uint256[] memory values',
            ') internal virtual override {',
            '    if (from != address(0) && !allowlistRegistry.isAllowed(from)) {',
            '        revert TransferNotAllowed(from, "Sender not in allowlist");',
            '    }',
            '    if (to != address(0) && !allowlistRegistry.isAllowed(to)) {',
            '        revert TransferNotAllowed(to, "Recipient not in allowlist");',
            '    }',
            '    super._update(from, to, ids, values);',
            '}',
          ].join('\n'),
        },
      ],
      lesson: '짧은 기간에 모든 것을 온체인으로 만들 수는 없었습니다. **무엇을 오프체인에 두고 무엇을 합의로 대체할지** 먼저 정하니 핵심 규칙에 집중할 수 있었습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'sanctions-screening',
      featured: true,
      span: 5,
      visual: 'screening',
      title: '제재 명단 스크리닝',
      category: 'AML · Compliance',
      org: '똑똑 현장실습',
      period: '2026.09',
      role: '설계 · 구현 · 테스트',
      team: '시장개발TFT',
      stack: ['Java · Spring Boot', 'React · TypeScript', 'Web Worker', 'Vitest · JUnit'],
      oneLiner: '동명이인 오탐은 줄이고, 표기 차이로 놓치던 대상은 찾는 제재 명단 대사 기능을 만들었습니다.',
      summary: '투자 대상과 거래 상대를 OFAC · UN · 금융위원회 제재 명단과 대사하는 기능입니다. **잘못 걸리는 것, 놓치는 것, 명단이 빠진 것** 세 가지 실패를 각각 막았습니다.',
      snapshot: {
        problem: '이름만 비교하면 동명이인이 대거 걸리고, 로마자 표기 차이 하나로 실제 대상을 놓칩니다. 명단이 빠지거나 오래되면 “해당 없음”이라는 결과 자체가 틀립니다.',
        approach: '이름 하나로 판정하지 않고 **생년월일 · 식별번호를 증거로** 더했습니다. 표기 변형은 규칙으로 흡수하고, 명단이 불완전하면 대사를 막았습니다.',
        result: '초기 실측에서 오탐을 **2.7% → 0.27%** 로 줄였고, 표기 변형 재현율을 **99.7%** 까지 올렸습니다.',
      },
      metrics: [
        { from: '2.7%', value: '0.27', unit: '%', label: '오탐률 (초기 실측)' },
        { from: '36.0%', value: '99.7', unit: '%', label: '표기 변형 재현율' },
      ],
      decisions: [
        { title: '잘못 걸리는 것 — 이름 하나로 판정하지 않습니다', body: '생년월일 · 식별번호를 증거로 함께 보고, 애매한 후보는 지우지 않고 접어 두어 최종 확정은 사람이 사유와 함께 합니다.' },
        { title: '놓치는 것 — 표기 차이를 규칙으로 흡수합니다', body: '두음법칙 · 음절 단위 변형 · 붙여쓰기 · 이름 순서를 정규화하고, 놓침을 줄일 때마다 늘어나는 오탐을 같은 표본에서 함께 쟀습니다.' },
        { title: '명단이 빠진 것 — 불완전하면 대사하지 않습니다', body: '금융위원회 고시를 출처로 더하고 UN 명단 인코딩 누락을 고쳤습니다. 출처가 빠지거나 7일이 지난 명단으로는 대사 자체를 막습니다.' },
      ],
      flow: [
        { k: '01', b: '명단 수집', s: 'OFAC · UN · 금융위 고시' },
        { k: '02', b: '무결성 · 신선도 검사', s: '빠지거나 오래되면 차단', key: true },
        { k: '03', b: '브라우저 대사', s: '엑셀은 서버로 보내지 않음' },
        { k: '04', b: '증거 결합', s: '이름 · 생년월일 · 식별번호' },
        { k: '05', b: '사람 확정', s: '사유 → 화이트리스트' },
      ],
      note: '사내 코드라 구조만 공개합니다.',
      lesson: '정확도 지표 하나만 올리면 다른 지표가 흔들립니다. **놓침과 오탐을 같은 표본에서 함께 재며** 결정했습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'healnexus',
      featured: true,
      span: 6,
      visual: 'signature',
      title: 'Healnexus 병원 관리자 플랫폼',
      category: 'Full-stack · Wallet Auth',
      org: '시노펙스',
      period: '2025.03 – 2026.02',
      role: '풀스택',
      team: '2인',
      stack: ['React · TypeScript', 'Node.js · Express', 'PostgreSQL', 'ethers.js'],
      oneLiner: '병원 관리자 플랫폼을 1년간 운영하며, 재사용할 수 없는 지갑 서명 로그인을 붙였습니다.',
      summary: '외국인 환자 예약 · 진료기록 · 다국어 알림을 다루는 병원 관리자 웹입니다. 회사의 블록체인 도입 논의에 맞춰 **비밀번호 대신 지갑 서명으로 로그인**하는 흐름을 넣었습니다.',
      snapshot: {
        problem: '병원마다 데이터를 분리해야 하고, 담당자는 상태 변경과 환자 알림을 따로 처리했습니다. 지갑 로그인은 서명할 메시지가 고정되면 탈취한 서명을 재사용할 수 있습니다.',
        approach: '권한을 3단계로 나눠 병원 단위로 격리하고, 알림을 상태 변경에 묶었습니다. 지갑 로그인은 **매번 새 nonce에 서명하게 하고 검증 즉시 폐기**했습니다.',
        result: '약 1년간 기능을 더하며 운영했고, 같은 서명으로 두 번 로그인할 수 없는 지갑 인증을 실제 서비스에 적용했습니다.',
      },
      metrics: [
        { value: '101', unit: '/ 131', label: '본인 커밋 (2025.03 – 2026.02)' },
        { value: '1', unit: '회용', label: '로그인 nonce' },
      ],
      decisions: [
        { title: '재사용할 수 없는 서명만 받습니다', body: '주소별 일회용 nonce에 서명하게 하고, 서명에서 복원한 주소가 일치하면 nonce를 즉시 지운 뒤 토큰을 발급합니다.' },
        { title: '병원 단위로 격리합니다', body: '슈퍼어드민 · 병원어드민 · 게스트 3단계 권한과 병원 단위 조회 조건으로 다른 병원의 데이터에 닿지 않게 했습니다.' },
        { title: '알림을 업무 흐름에 묶었습니다', body: '상태를 바꾸면 환자 언어로 번역된 문자가 함께 나가고, 의무기록은 짧게 만료되는 링크로만 내려보냅니다.' },
      ],
      flow: [
        { k: '01', b: 'nonce 발급', s: '주소별 일회용' },
        { k: '02', b: 'MetaMask 서명', s: '주소 + nonce' },
        { k: '03', b: '주소 복원 · 비교', s: 'verifyMessage', key: true },
        { k: '04', b: 'nonce 폐기', s: '재사용 차단' },
        { k: '05', b: '토큰 발급', s: '권한별 접근' },
      ],
      code: [
        {
          file: 'backend/routes/auth.js',
          caption: '복원한 주소가 요청 주소와 같을 때만 통과하고, 사용한 nonce는 바로 지웁니다.',
          snippet: [
            'router.post("/metamask-login", (req, res) => {',
            '  const { address, signature } = req.body;',
            '  const addr = address?.toLowerCase();',
            '  const nonce = loginNonces[addr];',
            '  if (!addr || !signature || !nonce)',
            '    return res.status(400).json({ message: "잘못된 요청" });',
            '',
            '  const msg = `Login\\n\\nAddress: ${addr}\\nNonce: ${nonce}`;',
            '  const recovered = verifyMessage(msg, signature).toLowerCase();',
            '  if (recovered !== addr)',
            '    return res.status(400).json({ message: "서명 검증 실패" });',
            '',
            '  delete loginNonces[addr]; // 1회용 사용 후 제거',
            '  const token = jwt.sign({ addr }, SECRET, { expiresIn: "12h" });',
            '  return res.json({ token });',
            '});',
          ].join('\n'),
        },
      ],
      note: '의료 데이터가 있어 저장소는 비공개입니다.',
      lesson: '첫 구현은 nonce를 메모리에 두었습니다. 지금 다시 만든다면 **암호학적 난수와 만료 시간이 있는 저장소**를 쓰겠습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'bitable',
      featured: true,
      span: 6,
      visual: 'latency',
      title: 'Bitable 음성 모의 거래소',
      category: 'Backend · Concurrency',
      org: '예강희망키움 PoC 해커톤',
      period: '2025.11 – 12',
      role: '백엔드',
      team: '팀 프로젝트',
      stack: ['Java 21', 'Spring Boot', 'PostgreSQL', 'AWS'],
      oneLiner: '시각장애인용 음성 모의 거래소에서, 느린 시세 조회와 잔고 이중 차감을 구조로 해결했습니다.',
      summary: '말 한마디로 모의 투자하는 거래소의 백엔드입니다. 화면을 보지 않는 사용자에게는 **지연과 “다시 시도”가 곧 실패**라서, 빠르고 틀리지 않는 거래에 집중했습니다.',
      snapshot: {
        problem: '모든 요청이 거래소 API를 직접 불러 응답이 느렸고, 자동매매와 음성 주문이 같은 계좌를 동시에 건드릴 수 있었습니다.',
        approach: '시세는 요청이 아니라 **스케줄러가 1초마다 가져와 캐시**에 두고, 잔고는 **비관적 락**으로 한 번에 한 거래만 차감하게 했습니다.',
        result: '시세 조회가 **150–300ms → 1ms 미만**이 됐고, 주문이 겹쳐도 잔고는 한 번만 차감됩니다.',
      },
      metrics: [
        { from: '150–300ms', prefix: '<', value: '1', unit: 'ms', label: '시세 조회' },
      ],
      decisions: [
        { title: '읽기는 캐시에서, 외부 호출은 한 곳에서', body: '스케줄러가 시세를 가져와 캐시를 바꾸고 요청은 캐시만 읽어, 외부 호출 수가 사용자 수와 무관해졌습니다. 최대 1초 지연은 모의 거래라 감수했습니다.' },
        { title: '재시도 대신 락을 택했습니다', body: '충돌하면 다시 시도해야 하는 방식은 음성 UI에 맞지 않아, 비관적 락으로 잔고를 지키고 락 안에서는 외부 API를 부르지 않게 했습니다.' },
        { title: '금액은 내림으로 계산합니다', body: '금액은 BigDecimal로 다루고 매수 수량은 내림 처리해 잔고를 넘는 매수가 생기지 않게 했습니다.' },
      ],
      flow: [
        { k: '01', b: '음성 입력', s: 'STT' },
        { k: '02', b: '의도 추출', s: 'GPT-4o-mini' },
        { k: '03', b: '거래 실행', s: '계좌 락 + 캐시 시세', key: true },
        { k: '04', b: '음성 응답', s: 'TTS' },
      ],
      lesson: '고른 기술만큼 **고르지 않은 기술과 그 이유**를 적어 두니, 설계를 설명할 때 흔들리지 않았습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'e2e-migration',
      featured: true,
      span: 6,
      visual: 'migration',
      title: 'E2E 테스트 Playwright 이관',
      category: 'QA Automation',
      org: '똑똑 현장실습',
      period: '2026.07 – 09',
      role: '이관 주도',
      team: 'TA',
      stack: ['Playwright', 'TypeScript', 'Qase', 'Slack'],
      oneLiner: '회귀 테스트 도구를 감이 아니라 분석으로 바꿔, 실행 시간과 라이선스 비용을 줄였습니다.',
      summary: 'Katalon으로 돌던 E2E 회귀 테스트를 Playwright로 옮겼습니다. **먼저 분석하고, PoC로 검증한 뒤, 단계적으로** 옮기는 순서를 지켰습니다.',
      snapshot: {
        problem: '회귀 테스트가 하루 6시간 넘게 걸리고 실행 라이선스 비용이 계속 들었습니다. 도구를 바꾸려 해도 옮길 범위를 알 수 없었습니다.',
        approach: '스크립트 호출을 **전수로 세어** 옮길 대상을 정하고, PoC로 이관 비용을 확인한 뒤 환경별 레인을 **병렬**로 돌렸습니다.',
        result: '실행 시간을 **70%** 줄이고 라이선스 비용을 **연 2,000달러** 절감했습니다.',
      },
      metrics: [
        { value: '70', unit: '%', label: '실행 시간 단축' },
        { prefix: '$', value: '2,000', unit: '/ 년', label: '라이선스 절감' },
      ],
      decisions: [
        { title: '바꾸기 전에 셌습니다', body: '470개 파일의 호출을 전수 집계해 대부분이 자체 키워드라는 것을 확인하고, 키워드부터 옮기는 순서를 정했습니다.' },
        { title: '검증하고 단계적으로 옮겼습니다', body: 'PoC로 이관 비용을 확인한 뒤 키워드 → 코어 → 비코어 순서로 옮겼습니다.' },
        { title: '병렬로 돌리고 실패만 남깁니다', body: '환경별 레인을 병렬로 실행하고, 실패한 테스트만 trace와 영상을 남겨 원인을 빠르게 찾게 했습니다.' },
      ],
      flow: [
        { k: '01', b: '전수 분석', s: '호출 집계' },
        { k: '02', b: 'PoC', s: '이관 비용 확인' },
        { k: '03', b: '레인 병렬 실행', s: '환경별 분리', key: true },
        { k: '04', b: '실패만 보존', s: 'trace · 영상' },
        { k: '05', b: '리포트', s: 'Qase · Slack' },
      ],
      note: '사내 코드와 환경 정보는 공개하지 않습니다.',
      lesson: '도구 전환을 **감이 아니라 호출 수 집계**에서 시작한 것이 이관 범위를 정하는 기준이 됐습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'utils-server',
      featured: true,
      span: 6,
      visual: 'hub',
      title: '사내 공용 유틸 서버',
      category: 'Backend · Architecture',
      org: '똑똑 현장실습',
      period: '2026.09',
      role: '설계 · 구현 · 제품 연동',
      team: '시장개발TFT',
      stack: ['Node · TypeScript', 'Fastify', 'SQLite', 'Docker'],
      oneLiner: '긴 작업을 요청에 붙잡아 두던 구조를, 여러 제품이 함께 쓰는 비동기 작업 서버로 바꿨습니다.',
      summary: '문서를 설명 영상으로 만드는 파이프라인을 여러 제품이 쓰는 서버로 옮겼습니다. **작업 계약을 먼저 정하고**, 설계부터 제품 연동까지 맡았습니다.',
      snapshot: {
        problem: '영상 한 편에 최대 50분이 걸리는데 제품은 요청을 30분까지 붙잡았고, 작업 공간을 공유해 다른 편의 화면과 나레이션이 오류 없이 섞일 수 있었습니다.',
        approach: '요청은 **즉시 접수만** 하고, **작업마다 폴더를 분리**해 계약으로 삼았으며, 성공의 기준을 결과 파일로 좁혔습니다.',
        result: '영상이 섞일 수 없는 구조가 됐고, 서버를 재시작해도 작업이 멈춘 단계부터 이어집니다.',
      },
      metrics: [
        { from: '요청 30분 대기', value: '202', unit: 'Accepted', label: '즉시 접수', count: false },
        { from: '7개', value: '3', unit: '개', label: '통합 후 컨테이너' },
      ],
      decisions: [
        { title: '요청은 붙잡지 않습니다', body: '접수하면 작업 id를 바로 돌려주고, 제품은 폴링으로 진행을 확인합니다. 끝나면 서명한 웹훅도 보냅니다.' },
        { title: '작업 폴더를 유일한 경계로 삼았습니다', body: '작업마다 입력 · 진행 · 결과 · 산출물 폴더를 분리해 섞일 수 없게 했고, 이 계약만 지키면 어떤 언어의 유틸도 붙습니다.' },
        { title: '성공의 정의를 좁혔습니다', body: '종료 코드만 보지 않고 결과 파일까지 있어야 성공으로 봅니다. 중간에 끊긴 ffmpeg이 재생되지 않는 영상을 남긴 실측이 근거입니다.' },
      ],
      flow: [
        { k: '01', b: '제품 백엔드', s: '서비스 키로 요청' },
        { k: '02', b: 'api', s: '즉시 접수 (202)' },
        { k: '03', b: 'worker', s: '작업 하나씩 집기', key: true },
        { k: '04', b: '유틸 실행', s: '작업별 폴더' },
        { k: '05', b: '결과 확인', s: '폴링 · 웹훅' },
      ],
      note: '사내 코드라 구조만 공개합니다.',
      lesson: '실패하고 도중에 죽는 **가짜 유틸로 워커 계약을 먼저 테스트**하니, 실제 파이프라인을 붙일 때 경계가 흔들리지 않았습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'compliance-reviewer',
      short: '한국·베트남 산업안전 법령에 비춰 사내 안전규정의 위반·누락을 찾는 LLM 검토 서비스',
      visual: 'regulation',
      title: '안전규정 컴플라이언스 리뷰어',
      category: 'LLM · RegTech',
      org: '시노펙스',
      period: '2026.05',
      role: '단독 개발',
      team: '1인',
      stack: ['FastAPI', 'Gemini', 'React · TypeScript', 'pdfplumber'],
      oneLiner: '사내 안전규정을 한국 · 베트남 법령에 비춰 검토하고, 모델의 판단을 근거 조문으로 확인하게 했습니다.',
      summary: '사내 안전규정이 한국 · 베트남 산업안전 법령을 지키는지 LLM으로 검토하는 서비스입니다. **모델의 판단을 근거 조문과 평가 수치로 확인할 수 있게** 만드는 데 집중했습니다.',
      snapshot: {
        problem: '두 나라 법령을 사람이 대조하기 어렵고, LLM이 인용한 조항은 원문과 대조할 수 없으면 업무에 쓸 수 없습니다.',
        approach: '법령을 **조문 단위 데이터**로 만들어 필요한 법령만 넘기고, 응답의 조항을 **원문에 다시 연결**하고, 전문가 라벨과 비교하는 평가를 붙였습니다.',
        result: '위반 사례는 모두 찾았고(재현율 1.00), 준수 문서의 오탐이 다음 과제라는 것을 수치로 확인했습니다.',
      },
      metrics: [
        { value: '718', unit: '개', label: '구조화한 법령 조문' },
        { value: '1.00', unit: '', label: '위반 사례 재현율 (표본 2건)' },
      ],
      decisions: [
        { title: '법령을 데이터로 만들었습니다', body: '한국 · 베트남 법령을 조문 단위로 구조화해, 국가를 고르면 필요한 법령만 모델에 넘깁니다.' },
        { title: '모델의 인용에 원문을 붙입니다', body: '응답의 조항 번호를 정규화해 조문 원문을 붙여, 사용자가 판단 옆에서 근거를 바로 확인합니다.' },
        { title: '평가로 한계를 드러냅니다', body: '전문가 라벨과 조항 단위로 비교해 재현율과 정밀도를 재고, 남은 과제를 수치로 확인했습니다.' },
      ],
      flow: [
        { k: '01', b: '문서 업로드', s: 'TXT · PDF · DOCX' },
        { k: '02', b: '법령 선택', s: '국가별 필터' },
        { k: '03', b: 'LLM 검토', s: 'JSON 응답', key: true },
        { k: '04', b: '조문 연결', s: '원문 첨부' },
        { k: '05', b: '결과', s: '위험도별 정리' },
      ],
      note: '법률 자문이 아닌 검토 보조 도구입니다.',
      lesson: 'LLM 결과는 **근거와 평가 수치가 함께 붙어야** 업무에 쓸 수 있습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'ivory',
      short: 'Lambda 클론 FaaS에서 함수 실행 단계를 실시간 여정으로 보여주는 프론트엔드',
      visual: 'pipeline',
      title: 'Ivory — 실행이 보이는 FaaS',
      category: 'Frontend · Realtime',
      org: 'Softbank 해커톤',
      period: '2025.11 – 12',
      role: '프론트엔드',
      team: '팀 프로젝트',
      stack: ['React · TypeScript', 'SSE', 'Framer Motion', 'S3 · CloudFront'],
      oneLiner: 'Lambda 클론 FaaS에서 함수 실행 과정을 실시간 “배송 여정”으로 보여주는 화면을 만들었습니다.',
      summary: 'EC2 러너에서 사용자 함수를 실행하는 Lambda 클론입니다. 실행 과정이 보이지 않는다는 문제를 **실시간 여정 화면**으로 풀었고, 저는 프론트엔드를 맡았습니다.',
      snapshot: {
        problem: '러너가 빨라 상태 이벤트가 한꺼번에 도착하면 단계별 화면이 건너뛰어져, 사용자는 결과만 보고 과정은 보지 못했습니다.',
        approach: '**데이터는 그대로 받되 화면만 늦췄습니다.** 상태를 큐에 쌓아 단계마다 최소 2초씩 재생했습니다.',
        result: '순식간에 지나가던 실행 과정을 단계별로 따라갈 수 있게 됐습니다.',
      },
      metrics: [
        { value: '49', unit: '/ 73', label: '프론트엔드 커밋 중 본인 작성' },
      ],
      decisions: [
        { title: '데이터가 아니라 표시를 늦췄습니다', body: '실행 건마다 상태 큐를 두고 순서대로 꺼내 보여줘, 정확성은 유지하면서 과정은 보이게 했습니다.' },
        { title: '스트림과 화면 상태를 나눴습니다', body: 'SSE 연결과 타임아웃은 서비스가, 로그 상태는 훅이 맡고 로그는 최근 1,000줄만 유지했습니다.' },
        { title: '배포를 자동화했습니다', body: '빌드부터 S3 배포, CloudFront 캐시 무효화까지 GitHub Actions로 한 번에 돌렸습니다.' },
      ],
      flow: [
        { k: '01', b: '코드 작성', s: '런타임 · 핸들러' },
        { k: '02', b: '러너 호출', s: 'EC2 Runner Pool' },
        { k: '03', b: 'SSE 스트림', s: '상태 · 로그' },
        { k: '04', b: '상태 큐', s: '단계당 최소 2초', key: true },
        { k: '05', b: '여정 화면', s: '애니메이션 · 로그' },
      ],
      links: [{ label: 'GitHub · Ivory-FE', url: 'https://github.com/Softbank-Ivory/Ivory-FE' }],
      lesson: '실시간 UI는 **이벤트가 도착하는 속도와 사람이 이해하는 속도가 다르다**는 점을 설계에 넣어야 했습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'd-light',
      short: '액세스 키 없이 사용자 AWS 계정을 연결하는 원클릭 배포 온보딩 화면',
      visual: 'accounts',
      title: 'D-light — 내 AWS 계정에 원클릭 배포',
      category: 'Frontend · Cloud Onboarding',
      org: 'Softbank 해커톤',
      period: '2025.11',
      role: '프론트엔드',
      team: '팀 프로젝트',
      stack: ['React · TypeScript', 'React Router', 'MSW', 'CloudFormation'],
      oneLiner: '레포를 고르면 사용자 본인의 AWS 계정에 배포하는 서비스에서, 키 없이 계정을 연결하는 온보딩 화면을 맡았습니다.',
      summary: '레포를 고르면 사용자 자신의 AWS 계정에 배포하는 서비스입니다. **액세스 키를 받지 않고** 계정을 연결하는 온보딩 흐름의 프론트엔드를 맡았습니다.',
      snapshot: {
        problem: '사용자 계정에 배포하려면 권한이 필요하지만, 자격 증명을 받는 순간 보안 부담이 서비스로 넘어옵니다.',
        approach: '사용자가 **CloudFormation 링크로 자기 계정에 역할을 만들면** 서비스가 그 역할로 배포합니다. 저는 토큰 발급부터 배포 확인까지의 화면 흐름을 만들었습니다.',
        result: '키를 한 번도 받지 않는 계정 연결부터 배포 상태 확인까지 이어지는 흐름을 완성했습니다.',
      },
      metrics: [
        { value: '20', unit: '/ 50', label: '프론트엔드 커밋 중 본인 작성' },
      ],
      decisions: [
        { title: '요청을 이어 붙여 기다림을 줄였습니다', body: '등록 토큰을 받으면 곧바로 Quick Create 링크를 요청해, 사용자가 기다리는 단계를 줄였습니다.' },
        { title: '백엔드를 기다리지 않았습니다', body: 'API를 먼저 목킹해 두고 화면을 병렬로 개발했습니다.' },
        { title: '인증 없이는 배포 단계에 들어올 수 없습니다', body: '보호 라우트로 로그인하지 않은 사용자를 막았습니다.' },
      ],
      flow: [
        { k: '01', b: '레포 선택', s: '프레임워크 감지' },
        { k: '02', b: '리전 선택', s: '배포 대상' },
        { k: '03', b: '역할 연결', s: 'Quick Create 링크', key: true },
        { k: '04', b: '콘솔 스택 생성', s: '콜백으로 연결 완료' },
        { k: '05', b: '배포', s: '상태 확인' },
      ],
      links: [{ label: 'GitHub · D-lite_FE', url: 'https://github.com/Softbank-Hackathon/D-lite_FE' }],
      lesson: '보안 설계가 좋아도 **단계가 많으면 사용자가 떠납니다.** 단계마다 무엇을 기다리는지 보여주는 화면이 중요했습니다.',
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'ai-sentinel',
      short: 'AI 에이전트 행동을 판정하고 해시로 감사하는 게이트웨이 설계와 UI 프로토타입',
      visual: 'orbit',
      title: 'AI Sentinel — 에이전트 감사 게이트웨이',
      category: 'Governance · Prototype',
      org: 'Kopilot 팀 과제',
      period: '2026.04 – 05',
      role: '감사 기록 설계 · UI 프로토타입',
      team: '팀 과제',
      stack: ['Next.js', 'React · TypeScript', 'Tailwind', 'shadcn/ui'],
      oneLiner: 'AI 에이전트의 행동을 판정하고 기록을 해시로 남기는 게이트웨이를 설계하고 프로토타입으로 보여줬습니다.',
      summary: 'AI 에이전트의 행동을 액션 단위로 판정하고 기록을 해시로 남기는 게이트웨이를 **설계**하고, 흐름을 보여주는 UI 프로토타입을 만들었습니다.',
      snapshot: {
        problem: '에이전트가 개인정보나 고위험 작업에 접근해도 사전에 통제할 지점이 없고, 사고 뒤 누가 무엇을 허용했는지 증명하기 어렵습니다.',
        approach: '요청을 액션 단위로 나눠 **허용 · 마스킹 · 사람 검토 · 거부**로 판정하고, 판정 기록을 해시로 온체인에 남기는 구조를 설계했습니다.',
        result: '시나리오별 판정 흐름을 재생하는 프로토타입으로 설계를 설명했습니다.',
      },
      metrics: [
        { value: '4', unit: '가지', label: '판정 유형' },
      ],
      decisions: [
        { title: '판정을 네 갈래로 나눴습니다', body: '허용과 거부 외에, 개인정보를 가리고 통과시키는 마스킹과 사람 승인을 두었습니다.' },
        { title: '기록은 바뀌지 않게 남깁니다', body: '판정 기록을 해시로 온체인에 앵커링해, 나중에 기록이 바뀌지 않았음을 보일 수 있게 설계했습니다.' },
      ],
      flow: [
        { k: '01', b: '에이전트 요청', s: '도구 호출' },
        { k: '02', b: '게이트웨이', s: '액션 단위 분해' },
        { k: '03', b: '정책 평가', s: 'RBAC · ABAC · AI', key: true },
        { k: '04', b: '판정', s: '허용 · 마스킹 · 검토 · 거부' },
        { k: '05', b: '감사 앵커링', s: '판정 해시 (설계)' },
      ],
      note: '정책 엔진 · 게이트웨이 · 블록체인 앵커링은 설계 단계이며 코드로 구현하지 않았습니다.',
    },
  ],

  experience: [
    {
      date: '2026.09 — 현재',
      org: '똑똑',
      role: '시장개발TFT · 현장실습',
      desc: '**제재 명단 스크리닝 기능**과 여러 제품이 함께 쓰는 **비동기 유틸 서버**를 만들었습니다.',
    },
    {
      date: '2026.07 — 2026.09',
      org: '똑똑',
      role: 'TA · 현장실습',
      desc: '회귀 테스트를 분석부터 시작해 Playwright로 옮기고, **실행 시간과 라이선스 비용**을 줄였습니다.',
    },
    {
      date: '2026.02',
      org: '한화미래금융공모전',
      role: 'Art-ABS 트랜치 RWA 컨트랙트',
      desc: '양도 · 권리 · 정산을 온체인 규칙으로 옮긴 스마트 컨트랙트를 만들었습니다.',
      badge: '2라운드 진출',
    },
    {
      date: '2025.11 — 2025.12',
      org: '예강희망키움 PoC 해커톤',
      role: 'Bitable · 백엔드',
      desc: '시세 캐시와 비관적 락으로 **빠르고 틀리지 않는 거래**를 만들었습니다.',
    },
    {
      date: '2025.11 — 2025.12',
      org: 'Softbank 해커톤',
      role: 'D-light · Ivory · 프론트엔드',
      desc: '키 없이 AWS 계정을 연결하는 온보딩과, 함수 실행 과정을 보여주는 화면을 만들었습니다.',
    },
    {
      date: '2025.02 — 현재',
      org: '시노펙스',
      role: 'AI인공신장사업팀 · 프리랜서',
      desc: '병원 관리자 플랫폼을 운영하며 **지갑 서명 로그인**을 붙였고, 안전규정 검토 서비스를 만들었습니다.',
    },
    {
      date: '2024.12 — 2025.01',
      org: 'KAIST 몰입캠프',
      role: '24W',
      desc: '매주 팀과 스택을 바꿔 개발했고, 러닝 게임 앱의 백엔드를 맡았습니다.',
    },
  ],

  education: [
    { label: 'Education', title: '고려대학교 컴퓨터학과', sub: '심화전공 · 2020.03 입학 · 2027.02 졸업 예정' },
    { label: 'Certificates', title: 'SQLD · ADsP', sub: '2025.09 취득' },
    { label: 'Language', title: 'OPIc AL · TOEIC 870', sub: '영어' },
  ],
};
