/* Portfolio content. Text supports **bold** and `code`. Avoid ASCII single quotes inside strings. */
window.PORTFOLIO = {
  profile: {
    name: '고상혁',
    nameEn: 'Sanghyuk Ko',
    email: '90sangko@naver.com',
    github: 'https://github.com/sanghyuk-ko',
  },

  hero: {
    lines: ['PROOF', 'OVER PROMISE'],
    linesMobile: ['PROOF', 'OVER', 'PROMISE'],
    evidence: [
      '_update() → allowlist.isAllowed(to) || revert',
      'oracle 2 of 3 · amount && docHash must match',
      'senior 6% → mezzanine 9% → equity residual',
      'false positive 2.7% → 0.27%',
      'verifyMessage(msg, sig) == addr → delete nonce',
      'quote latency 150–300ms → <1ms',
      'e2e runtime −70% · license −$2,000 / yr',
      'sanction list age > 7d → screening blocked',
    ],
  },

  marquee: ['RWA', 'ERC-1155', 'KYC Allowlist', 'Sanctions Screening', 'Solidity', 'Foundry', 'Spring Boot', 'TypeScript'],

  projects: [
    /* ------------------------------------------------------------------ */
    {
      id: 'art-abs',
      featured: true,
      span: 7,
      visual: 'tranche',
      title: 'Art-ABS 트랜치 컨트랙트',
      category: 'RWA · Smart Contract',
      org: '한화 공모전',
      period: '2026.02',
      role: '컨트랙트 설계 · 구현 · 테스트',
      team: '3인 팀',
      stack: ['Solidity 0.8.24', 'Foundry', 'OpenZeppelin', 'ERC-1155', 'React · ethers v6'],
      oneLiner: '미술품 담보 ABS를 Senior·Mezzanine·Equity 토큰으로 나누고, 양도·상태 전이·정산을 온체인 규칙으로 통제했습니다.',
      summary: '미술품 담보 ABS에서 분쟁이 생기는 **양도·권리·정산** 세 지점을 골라, 각각을 컨트랙트 규칙으로 옮긴 RWA MVP입니다. 한화 공모전 2라운드에 진출했습니다.',
      metrics: [
        { value: '4', unit: '개', label: '책임별로 나눈 컨트랙트' },
        { value: '1,046', unit: '줄', label: 'Solidity 코드' },
        { value: '2', unit: 'of 3', label: '수입·비용 기록에 필요한 오라클 합의', count: false },
        { value: '41', unit: '개', label: 'Foundry 테스트' },
      ],
      overview: [
        '미술품을 기초자산으로 한 ABS를 토큰으로 발행한다고 하면 대개 “토큰화” 자체에 집중합니다. 저는 실제로 문제가 되는 곳이 발행 이후라고 봤습니다. **누가 보유할 수 있는지(양도), 딜이 지금 어느 단계인지(권리), 수익을 어떤 순서로 나누는지(정산)** 입니다.',
        '그래서 세 지점을 각각 하나의 컨트랙트 책임으로 나누고, KYC를 통과한 지갑을 관리하는 레지스트리를 더해 네 개의 컨트랙트로 구성했습니다.',
      ],
      problem: [
        'KYC를 거치지 않은 지갑이 트랜치 토큰을 **보유하거나 전달받으면 안 됩니다.** 발행 시점만 막으면 2차 전송에서 뚫립니다.',
        '매각 같은 중요한 상태 전이를 **한 사람이 단독으로** 실행할 수 있으면 권리 분쟁의 여지가 생깁니다.',
        '임대 수입과 비용을 누가 어떤 근거로 기록했는지 **나중에 검증할 수 없으면** 정산 결과를 신뢰할 수 없습니다.',
      ],
      decisions: [
        {
          title: '양도 — 모든 전송 경로에 허용목록 훅을 겁니다',
          body: 'ERC-1155의 `_update` 훅을 오버라이드했습니다. 민팅·전송·소각이 모두 이 함수를 지나가므로, 여기서 보내는 쪽과 받는 쪽을 `AllowlistRegistry`로 검사하고 허용되지 않은 지갑이면 `TransferNotAllowed`로 전송 자체를 되돌립니다.',
          why: '→ 발행 시점이 아니라 토큰이 움직이는 모든 순간을 통제 지점으로 삼았습니다.',
        },
        {
          title: '권리 — 상태 전이에 서명자 합의를 요구합니다',
          body: '`FUNDRAISING → ACTIVE_LEASE → SALE_REVIEW → SALE_EXECUTED → SETTLED` 5단계 상태머신을 두고, 매각 단계는 지정된 서명자들의 승인이 기준 수에 도달해야만 전이합니다. 승인할 때 근거 문서 해시를 함께 제출하고, 같은 서명자의 중복 승인은 막으며, 전이가 끝나면 승인 상태를 초기화합니다.',
          why: '→ 한 사람의 판단이 아니라 합의가 딜의 상태를 바꾸게 했습니다.',
        },
        {
          title: '정산 — 오라클 3명 중 2명이 금액과 문서 해시를 맞춰야 기록합니다',
          body: '가격 오라클을 흉내 내는 대신, 수입과 비용을 **증빙 문서 해시와 함께 선언**하게 했습니다. 두 번째 오라클이 다른 금액이나 다른 해시를 내면 `DataMismatch`·`DocHashMismatch`로 되돌리고, 두 명이 일치해야 해당 기간의 수입으로 확정됩니다.',
          why: '→ 외부 데이터를 믿는 대신, 불일치가 드러나는 구조를 택했습니다.',
        },
        {
          title: '워터폴 — 우선순위대로 나누고 리포트 해시를 남깁니다',
          body: '확정된 순수익을 Senior(연 6%의 월할) → Mezzanine(연 9%의 월할) → Equity(잔여) 순서로 분배합니다. 앞 순위를 채우지 못하면 뒤 순위는 받지 못하고, 정산 리포트 해시는 이벤트로 남깁니다. 투자자는 보유 비율대로 청구합니다.',
        },
      ],
      flow: [
        { k: '01', b: 'AllowlistRegistry', s: 'KYC 통과 지갑 등록' },
        { k: '02', b: 'TrancheToken', s: 'ERC-1155 id 0·1·2, 전송마다 검사' },
        { k: '03', b: 'DealStateMachine', s: '5단계 전이 · 서명자 승인', key: true },
        { k: '04', b: 'Oracle 2-of-3', s: '수입·비용 + 문서 해시' },
        { k: '05', b: 'WaterfallSettlement', s: '우선순위 분배 · 리포트 해시' },
        { k: '06', b: 'Claim', s: '보유 비율대로 청구' },
      ],
      code: [
        {
          file: 'src/TrancheToken.sol',
          caption: '민팅·전송·소각이 모두 지나가는 `_update` 훅 하나에서 양쪽 지갑을 검사합니다.',
          snippet: [
            'function _update(',
            '    address from,',
            '    address to,',
            '    uint256[] memory ids,',
            '    uint256[] memory values',
            ') internal virtual override {',
            '    // 민팅(from=0) 및 버닝(to=0) 시에는 수령자만 검증',
            '    if (from != address(0) && !allowlistRegistry.isAllowed(from)) {',
            '        emit TransferBlocked(from, to, ids[0], "Sender not in allowlist");',
            '        revert TransferNotAllowed(from, "Sender not in allowlist");',
            '    }',
            '',
            '    if (to != address(0) && !allowlistRegistry.isAllowed(to)) {',
            '        emit TransferBlocked(from, to, ids[0], "Recipient not in allowlist");',
            '        revert TransferNotAllowed(to, "Recipient not in allowlist");',
            '    }',
            '',
            '    super._update(from, to, ids, values);',
            '}',
          ].join('\n'),
        },
        {
          file: 'src/WaterfallSettlement.sol',
          caption: '두 번째 오라클부터는 금액과 문서 해시가 첫 제안과 같아야 합니다. 승인이 기준 수에 닿는 순간 기간 수입이 확정됩니다.',
          snippet: [
            'function proposeIncome(uint256 period, uint256 amount, bytes32 documentHash)',
            '    external onlyRole(ORACLE_ROLE)',
            '{',
            '    // … 딜 상태 · 중복 기록 검사 생략',
            '    OracleSubmission storage submission = pendingIncome[period];',
            '',
            '    // 첫 번째 제안이 아니면 데이터 일치 검증',
            '    if (submission.approvalCount > 0) {',
            '        if (submission.amount != amount) revert DataMismatch(submission.amount, amount);',
            '        if (submission.docHash != documentHash) revert DocHashMismatch(submission.docHash, documentHash);',
            '    } else {',
            '        submission.amount = amount;',
            '        submission.docHash = documentHash;',
            '    }',
            '',
            '    if (submission.hasApproved[msg.sender]) revert AlreadyApproved(msg.sender);',
            '    submission.hasApproved[msg.sender] = true;',
            '    submission.approvalCount++;',
            '',
            '    // 2명 이상 승인 시 확정',
            '    if (submission.approvalCount >= REQUIRED_ORACLE_APPROVALS) {',
            '        periodReports[period].grossIncome = amount;',
            '        periodReports[period].incomeDocHash = documentHash;',
            '        periodReports[period].incomeRecorded = true;',
            '        submission.isComplete = true;',
            '        emit IncomeRecorded(period, amount, documentHash, msg.sender, block.timestamp);',
            '    }',
            '}',
          ].join('\n'),
        },
      ],
      results: [
        { b: '분쟁 지점 3곳을 규칙으로', t: '양도는 전송 훅, 권리는 서명 기반 상태머신, 정산은 오라클 합의와 워터폴로 대응시켰습니다.' },
        { b: '범위를 명시적으로 잘랐습니다', t: 'KYC 판정은 오프체인, 가격은 오라클 대신 문서 해시와 승인, 업그레이드 대신 불변 컨트랙트를 택하고 그 이유를 문서에 남겼습니다.' },
        { b: '한화 공모전 2라운드 진출', t: '컨트랙트와 함께 React·ethers 데모 화면으로 시나리오를 시연했습니다.' },
      ],
      lessons: [
        '공모전 기간 안에 모든 것을 온체인으로 만들 수는 없었습니다. **무엇을 오프체인에 두고 무엇을 합의로 대체할지** 먼저 정하니, 남은 규칙을 끝까지 테스트할 수 있었습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'sanctions-screening',
      featured: true,
      span: 5,
      visual: 'screening',
      title: '제재 명단 스크리닝',
      category: 'AML · Compliance',
      org: '똑똑 현장실습',
      period: '2026.09',
      role: '명단 파서 · 대사 로직 · 검토 화면 · 평가 도구 · 테스트',
      team: '시장개발TFT',
      stack: ['Java 25 · Spring Boot 3.5', 'React 19 · TypeScript', 'Web Worker', 'Vitest · JUnit', 'SheetJS'],
      oneLiner: '투자 대상과 거래 상대를 OFAC·UN·금융위원회 고시 제재 명단과 FATF 고위험국에 대사하는 기능을 명단 파서부터 검토 화면까지 만들었습니다.',
      summary: 'VC 실무자용 도구 플랫폼에 들어간 **제재 명단 대사 기능**입니다. 이름이 비슷하다는 이유만으로 걸리는 오탐은 줄이고 표기 차이로 놓치는 대상은 찾아내며, 명단이 불완전하거나 오래되면 **대사를 아예 막도록** 설계했습니다.',
      metrics: [
        { from: '2.7%', value: '0.27', unit: '%', label: '오탐률 — 생년월일 2차 확인 (초기 실측, 한국 인명 1,500명)' },
        { from: '36.0%', value: '99.7', unit: '%', label: '남한식 표기 변형 재현율 (5,843건)' },
        { from: '430ms', value: '75', unit: 'ms', label: '1인당 대사 시간 (2026-09-16 실측)' },
        { value: '155', unit: '건', label: '금융위 고시 대상 1,066건 중 OFAC·UN에 없던 대상' },
        { value: '292', unit: '개', label: '테스트 (프론트 217 · Java 75)' },
      ],
      overview: [
        'VC 실무에서는 투자 대상과 거래 상대가 제재 대상인지 확인해야 합니다. 이름 유사도만으로 판단하면 동명이인이 대거 걸리고, 반대로 로마자 표기 차이 하나 때문에 실제 대상을 놓칩니다. 명단 자체가 빠져 있으면 “해당 없음”이라는 결과부터 틀립니다.',
        '저는 OFAC SDN · 비SDN · UN · 금융위원회 고시를 읽는 Java 파서부터, 사용자가 올린 엑셀을 브라우저 안에서 정규화하고 대사하는 로직, 결과를 사람이 확정하는 검토 화면, 평가셋과 테스트까지 맡았습니다. 메인 브랜치에 병합된 스크리닝 커밋 17개는 모두 제가 작성했습니다.',
      ],
      problem: [
        '이름 유사도만으로 판단하면 **오탐이 2.7%** 였습니다. 실무자가 매번 손으로 걸러야 하는 수준입니다.',
        '두음법칙 표기 차이로 **121명 중 50명을 놓쳤고**, 남한식 표기 변형은 36.0%만 찾았습니다. 성과 이름을 붙여 쓴 입력은 47%, 법인 접미어를 생략하거나 약어로 쓰면 42%와 71%만 찾았습니다.',
        'SDN 명단만 쓰면 비SDN 표본 121명 중 **22명만 탐지**되고, 표본의 CMIC 대상은 모두 빠졌습니다.',
        'UN 명단은 비ASCII 이름 193건 중 **161건이 인코딩 문제로 깨져** 조용히 빠졌고, 금융위원회 고시 대상 1,066건 중 **155건은 OFAC·UN 어디에도 없었습니다.** 명단이 빠지거나 오래된 채 대사하면 “해당 없음”이라는 결과 자체가 틀린 결과가 됩니다.',
      ],
      decisions: [
        {
          title: '이름 점수와 판단을 나누고, 후보는 지우지 않고 접습니다',
          body: '이름 점수는 편집거리·발음·순서로 계산하고, 판단은 별도 단계에서 합니다. 명단의 생년과 1년 넘게 차이 나면 후보를 지우지 않고 “생년 충돌”로 접어 두고, 비동일인 확정은 사람이 사유와 함께 하게 했습니다. 초기 실측에서 이 2차 확인으로 오탐이 **2.7%에서 0.27%** 로 줄었습니다.',
          why: '→ 점수를 억지로 깎지 않고, 판단에 쓰는 근거를 하나 더 늘렸습니다.',
        },
        {
          title: '이름 하나로 판정하지 않습니다',
          body: '사람이 판정한 일치 105쌍 중 놓친 16쌍의 6쌍은 생년월일까지 같았습니다. 그래서 이름 · 생년월일 · 식별번호를 증거로 함께 보고, 사람 합의셋으로 가중치를 맞춘 점수로 우선 확인 · 검토 · 신원 충돌 구간을 매깁니다. 기존에 이름으로 걸리던 검출은 빼지 않고 더하기만 했습니다.',
        },
        {
          title: '놓침을 줄일 때마다 오탐 대가를 같이 잽니다',
          body: '두음 변형을 넣자 두음 미탐은 50명에서 **0명**이 됐지만, 생년월일 확인 후 오탐도 1,500명 중 3건에서 9건으로 늘었습니다. 표기법 접기도 같은 표본으로 재어 4명에서 7명으로 느는 것을 확인했습니다. 두 수치를 같은 주석에 남기고, 놓침을 줄이는 쪽을 택했습니다.',
        },
        {
          title: '알고리즘은 3종만 남기고 점수를 나눠 보여줍니다',
          body: '상용 제품은 유사도 알고리즘을 7종 쓰지만, 한국어 로마자 실측에서 나머지 4종은 같은 사람보다 다른 사람에게 더 높은 점수를 줘 3종만 남겼습니다. 화면에서는 점수를 철자 · 순서 · 발음으로 나눠 보여줘 왜 걸렸는지 확인할 수 있게 했습니다.',
        },
        {
          title: '명단이 불완전하거나 오래되면 대사하지 않습니다',
          body: '필수 출처가 하나라도 빠지거나 수집한 지 7일이 지나면 서버가 503으로 거부하고, 화면도 대사와 결과 다운로드를 막습니다. 30초마다, 탭에 돌아올 때, 파일 열기 · 다운로드 · 확정 직전에 다시 검사합니다.',
          why: '→ 틀린 “통과”보다 명시적인 “불가”가 안전하다고 봤습니다.',
        },
        {
          title: '빠르게 하되 검출은 잃지 않습니다',
          body: '후보 색인으로 질의당 226ms를 35.7ms로 줄이고, 질의 1,052건에서 전수 대조와 검출 결과가 같음을 확인했습니다. 19.5ms까지 줄이는 안은 실제 검출 1건을 잃어 채택하지 않았습니다. 같은 토큰 계산을 되풀이하지 않게 해 1인당 대사는 430ms에서 75ms가 됐고, 대사는 Web Worker에서 돌려 화면이 멈추지 않습니다.',
        },
        {
          title: '출처를 넓히고 번호 충돌을 막았습니다',
          body: 'OFAC SDN에 비SDN · UN · 금융위원회 고시를 더했습니다. 비SDN 대상 481개 중 93개가 SDN과 번호가 같아, 화이트리스트 한 줄이 서로 다른 두 대상을 함께 풀지 않도록 비SDN 번호에 `NS-` 접두어를 붙였습니다. UN 명단은 바이트로 읽도록 고쳐 라이브 41,270건에서 깨진 이름 0건을 확인했습니다.',
        },
      ],
      flow: [
        { k: '01', b: '명단 수집', s: 'OFAC SDN · 비SDN · UN · 금융위 고시, FATF 국가' },
        { k: '02', b: '무결성 · 신선도', s: '출처 누락 · 7일 초과 시 503', key: true },
        { k: '03', b: '엑셀 정규화', s: '브라우저 안, 로마자로 읽을 수 없는 입력은 반려' },
        { k: '04', b: '후보 색인 → 이름 점수', s: 'Web Worker에서 대사' },
        { k: '05', b: '증거 결합', s: '이름 · 생년월일 · 식별번호 → 검토 구간' },
        { k: '06', b: '사람 확정', s: '사유 필수 → 화이트리스트 (영문명 + 생년월일)' },
      ],
      flowNote: '데이터 경계는 브라우저입니다. 사용자가 올린 엑셀은 서버로 보내지 않고 브라우저 안에서 대사하며, 결과 파일에는 출처별 수집 시각과 건수를 함께 남깁니다.',
      results: [
        { b: '오탐 2.7% → 0.27%', t: '초기 실측에서 생년월일 2차 확인으로 동명이인 오탐을 10분의 1로 줄였습니다.' },
        { b: '표기 차이로 놓치던 대상 탐지', t: '두음 미탐 50명 → 0명, 남한식 표기 변형 재현율 36.0% → 99.7%, 붙여쓰기 47% → 100%, 이름 순서가 뒤집힌 입력 150명 전원 탐지.' },
        { b: '빠지던 명단 복구', t: 'UN 명단 인코딩 결함으로 누락되던 161건을 되살리고, 금융위 고시를 더해 OFAC · UN에 없던 155건을 대사합니다.' },
        { b: '1인당 430ms → 75ms', t: '후보 색인과 계산 재사용으로 속도를 높이되, 전수 대조와 결과가 같은지 확인했습니다.' },
        { b: '테스트 292개', t: '프론트 217개와 Java 75개로 파서 · 정규화 · 판단 규칙 · 화면을 고정했습니다.' },
      ],
      note: '사내 코드라 원문 대신 구조와 실측 수치로 정리했습니다. 수치마다 측정 시점과 표본이 다르며, 코드 주석에 조건과 함께 기록했습니다.',
      lessons: [
        '정확도 지표 하나만 올리면 다른 지표가 흔들립니다. **미탐과 오탐을 같은 표본에서 함께 재고**, 수치는 실측 조건과 함께 코드 옆에 남겼습니다.',
        '규칙을 만든 데이터에서 0%가 나오면 과적합부터 의심했습니다. **설계에 쓰지 않은 음절로 따로 재서** 놓침이 11.0%에서 5.2%로 줄어든 것을 확인했습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'healnexus',
      featured: true,
      span: 6,
      visual: 'signature',
      title: 'Healnexus 병원 관리자 플랫폼',
      category: 'Full-stack · Wallet Auth',
      org: '시노펙스',
      period: '2025.03 – 2026.02',
      role: '풀스택 (131커밋 중 101개)',
      team: '2인',
      stack: ['React 19 · TypeScript', 'Node.js · Express', 'PostgreSQL', 'AWS S3', 'ethers v6'],
      oneLiner: '외국인 환자 예약·진료기록·다국어 알림을 다루는 병원 관리자 웹을 만들고, MetaMask 서명 로그인을 붙였습니다.',
      summary: '병원별로 데이터를 격리해야 하는 **멀티테넌트 관리자 플랫폼**입니다. 회사의 블록체인 도입 논의에 맞춰 **지갑 서명 기반 로그인**을 구현했습니다.',
      metrics: [
        { value: '101', unit: '커밋', label: '전체 131커밋 중 본인 작성' },
        { value: '4', unit: '개 언어', label: 'UI 지원 언어 (마스터 데이터는 5개 언어 자동 번역)' },
        { value: '10', unit: '분', label: '의무기록 Presigned URL 만료' },
        { value: '1', unit: '회용', label: '지갑 로그인 nonce, 검증 즉시 폐기' },
      ],
      overview: [
        '외국인 환자를 받는 병원이 예약 상태를 바꾸고, 진료기록을 올리고, 환자 언어로 문자를 보내는 일을 한 화면에서 처리하도록 만든 관리자 웹입니다. 슈퍼어드민 · 병원어드민 · 게스트 3단계 권한으로 병원 단위 데이터를 격리했습니다.',
        '2025년 회사에서 블록체인 도입이 논의되면서 Solidity를 공부했고, 그 첫 적용으로 비밀번호 대신 **지갑 서명으로 로그인**하는 흐름을 넣었습니다.',
      ],
      problem: [
        '병원 담당자가 **상태 변경과 환자 문자 발송(번역 포함)을 따로** 해야 했습니다.',
        '병원명 표기 차이 때문에 **승인과 노출이 어긋나는** 일이 생겼습니다.',
        '지갑 로그인에서 서명할 메시지가 고정돼 있으면 **한 번 탈취한 서명을 재사용**할 수 있습니다.',
      ],
      decisions: [
        {
          title: '로그인마다 새 nonce에 서명하게 했습니다',
          body: '주소별로 일회용 nonce를 발급하고, 사용자는 주소와 nonce가 담긴 메시지에 서명합니다. 서버는 ethers `verifyMessage`로 서명에서 주소를 복원해 요청 주소와 비교하고, 일치하면 **nonce를 즉시 지운 뒤** JWT를 발급합니다.',
          why: '→ 같은 서명으로 두 번 로그인할 수 없습니다.',
        },
        {
          title: '알림을 상태 변경에 묶었습니다',
          body: 'Naver SENS 요청 서명(HMAC-SHA256)을 직접 구현하고, 90byte를 넘으면 SMS를 LMS로 자동 전환합니다. 번역 입력에는 500ms 디바운스를 걸어 호출을 줄였습니다.',
        },
        {
          title: '민감 문서는 짧게만 열어 줍니다',
          body: '의무기록은 S3에 두고 10분 뒤 만료되는 Presigned URL로만 내려보냅니다. 게스트는 2-way OTP로 인증합니다.',
        },
        {
          title: '병원 단위로 격리했습니다',
          body: '조회마다 병원 단위 조건을 걸고 승인 처리는 트랜잭션으로 묶었습니다. 환자별 최신 기록은 CTE와 `ROW_NUMBER() OVER (PARTITION BY …)`로 뽑습니다.',
        },
      ],
      flow: [
        { k: '01', b: 'POST /nonce', s: '주소별 일회용 nonce 발급' },
        { k: '02', b: 'MetaMask 서명', s: '주소 + nonce 메시지' },
        { k: '03', b: 'verifyMessage', s: '서명에서 주소 복원 · 비교', key: true },
        { k: '04', b: 'nonce 폐기', s: '재사용 차단' },
        { k: '05', b: 'JWT 12h', s: '권한별 라우트 접근' },
      ],
      code: [
        {
          file: 'backend/routes/auth.js',
          caption: '복원한 주소가 요청 주소와 같을 때만 통과하고, 사용한 nonce는 바로 지웁니다.',
          snippet: [
            'router.post("/metamask-login", (req, res) => {',
            '  const { address, signature } = req.body;',
            '  const addr = address?.toLowerCase();',
            '  const nonce = loginNonces[addr];',
            '',
            '  if (!addr || !signature || !nonce)',
            '    return res.status(400).json({ message: "잘못된 요청" });',
            '',
            '  const msg = `Login\\n\\nAddress: ${addr}\\nNonce: ${nonce}`;',
            '  const recovered = verifyMessage(msg, signature).toLowerCase();',
            '',
            '  if (recovered !== addr)',
            '    return res.status(400).json({ message: "서명 검증 실패" });',
            '',
            '  delete loginNonces[addr]; // 1회용 사용 후 제거',
            '  const token = jwt.sign({ addr }, SECRET, { expiresIn: "12h" });',
            '  return res.json({ token });',
            '});',
          ].join('\n'),
        },
      ],
      results: [
        { b: '1년 가까이 운영한 제품', t: '2025년 3월부터 2026년 2월까지 기능을 더하며 101개 커밋을 남겼습니다.' },
        { b: '백엔드 약 4,000줄 · 프론트 약 9,100줄', t: '핵심 테이블 6개, 외부 연동 4종(S3 · SENS · SMTP · 번역).' },
        { b: 'EVM 서명 인증 적용', t: '서명 → 주소 복원 → nonce 폐기로 이어지는 지갑 인증을 실제 서비스에 붙였습니다.' },
      ],
      note: '의료 데이터와 고객사 정보가 있어 저장소는 비공개입니다.',
      lessons: [
        '첫 구현은 nonce를 메모리에 두고 `Math.random`으로 만들었습니다. 지금 다시 만든다면 **암호학적 난수와 만료 시간이 있는 저장소**를 쓰겠습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'bitable',
      featured: true,
      span: 6,
      visual: 'latency',
      title: 'Bitable 음성 모의 거래소',
      category: 'Backend · Concurrency',
      org: '예강희망키움 PoC 해커톤',
      period: '2025.11 – 12',
      role: '백엔드 (커밋 61개 중 57개)',
      team: '팀 프로젝트',
      stack: ['Java 21', 'Spring Boot 3.2', 'WebClient', 'PostgreSQL', 'AWS'],
      oneLiner: '시각장애인이 음성으로 모의 투자하는 거래소의 백엔드를 만들었습니다. 시세 조회를 150–300ms에서 1ms 미만으로 줄였습니다.',
      summary: '음성 명령 하나를 **STT → 의도 분류 → 거래 실행 → TTS**로 처리하는 모의 암호화폐 거래소입니다. 화면을 보지 않는 사용자에게는 지연과 “다시 시도”가 곧 실패라서, **빠르고 이중 차감이 없는 거래**에 집중했습니다.',
      metrics: [
        { from: '150–300ms', prefix: '<', value: '1', unit: 'ms', label: '시세 조회 지연' },
        { value: '1', unit: '회/초', label: 'Upbit 호출 수 (사용자 수와 무관)' },
        { value: '57', unit: '/ 61', label: '백엔드 커밋 중 본인 작성' },
      ],
      overview: [
        '시각장애인을 위한 음성 기반 모의 투자 서비스입니다. 사용자가 말하면 CLOVA STT로 받아쓰고, GPT-4o-mini로 의도와 종목·수량을 뽑고, 빈 항목이 있으면 다시 묻고, 거래를 실행한 뒤 CLOVA TTS로 결과를 들려줍니다.',
        '저는 백엔드를 맡아 음성 파이프라인, 거래 로직, 시세 캐시, 배포까지 담당했습니다.',
      ],
      problem: [
        '시세가 필요한 모든 요청이 Upbit를 직접 호출해 **요청마다 150–300ms 지연**이 생겼고, 사용자가 늘면 Rate Limit에 걸릴 위험이 있었습니다.',
        'WebClient를 호출마다 새로 만들어 **커넥션 풀과 타임아웃이 없었습니다.**',
        '자동매매 스케줄러와 음성 주문이 **같은 계좌에 동시에 접근**할 수 있었습니다.',
      ],
      decisions: [
        {
          title: '시세는 요청이 아니라 스케줄러가 가져옵니다',
          body: '`@Scheduled(fixedRate = 1000)` 백그라운드 폴링으로 `AtomicReference` 캐시를 채우고, 요청은 캐시만 읽습니다. 갱신에 실패하면 이전 캐시를 유지합니다. Redis 같은 외부 인프라는 늘리지 않았고, 최대 1초의 시세 지연은 모의 거래라는 성격상 감수했습니다.',
          why: '→ 외부 API 호출 횟수가 사용자 수와 무관해졌습니다.',
        },
        {
          title: '잔고는 비관적 락으로 지킵니다',
          body: '`PESSIMISTIC_WRITE`(SELECT … FOR UPDATE)로 잔고 이중 차감을 막았습니다. 낙관적 락은 충돌하면 트랜잭션 전체를 재시도해야 하는데, 음성 UI에서 “다시 시도해 주세요”를 들려줄 수는 없었습니다. 락 안에서는 외부 API를 부르지 않도록 캐시를 앞에 뒀습니다.',
        },
        {
          title: 'WebClient를 역할별 Bean으로 분리했습니다',
          body: '연결 5초, 읽기·쓰기 30초 타임아웃과 10MB 버퍼를 명시하고, Upbit 요청은 100개 단위로 나눠 보냅니다.',
        },
        {
          title: '금액은 BigDecimal로 계산합니다',
          body: 'KRW는 scale 2, 코인 수량은 scale 8로 두고 매수 수량은 `RoundingMode.DOWN`으로 내려 잔고를 넘는 매수를 원천 차단했습니다.',
        },
      ],
      flow: [
        { k: '01', b: 'POST /api/voice/audio', s: '음성 입력' },
        { k: '02', b: 'CLOVA STT', s: '받아쓰기' },
        { k: '03', b: 'GPT-4o-mini', s: '의도 · 항목 추출, 빈 항목 재질문' },
        { k: '04', b: 'TradingService', s: '계좌 락 + 캐시 시세로 체결', key: true },
        { k: '05', b: 'CLOVA TTS', s: '결과 음성 응답' },
      ],
      flowNote: '백그라운드에서는 1초마다 시세 캐시를 갱신하고, 매 정시 포트폴리오 스냅숏을 남기며, 가격 알림이 자동매매를 실행합니다.',
      code: [
        {
          file: 'service/marketdata/MarketDataService.java',
          caption: 'Upbit 호출은 1초마다 스케줄러 한 곳에서만 일어나고, 요청 스레드는 캐시를 읽기만 합니다.',
          snippet: [
            '// Thread-safe한 캐시 저장소 (초기값은 빈 리스트)',
            'private final AtomicReference<List<MarketData>> marketDataCache =',
            '        new AtomicReference<>(Collections.emptyList());',
            '',
            '/**',
            ' * 1초마다 시세 데이터 갱신 (Background Polling)',
            ' */',
            '@Scheduled(fixedRate = 1000)',
            'public void refreshMarketData() {',
            '    try {',
            '        // 1. DB에 등록된 코인 목록 조회',
            '        List<Coin> allCoins = coinService.getAllCoins();',
            '        List<String> symbols = allCoins.stream()',
            '                .map(Coin::getSymbol)',
            '                .collect(Collectors.toList());',
            '        if (symbols.isEmpty()) {',
            '            return;',
            '        }',
            '        // 2. Upbit API 호출',
            '        List<MarketData> result = upbitClient.getTicker(symbols);',
            '        // … 이름 매핑 후 캐시 교체',
          ].join('\n'),
        },
      ],
      results: [
        { b: '시세 조회 1ms 미만', t: '요청마다 150–300ms 걸리던 조회가 메모리 캐시 조회로 바뀌었습니다.' },
        { b: '이중 차감 차단', t: '자동매매와 음성 주문이 겹쳐도 잔고는 한 번만 차감됩니다.' },
        { b: '한계를 문서로 남김', t: '최대 1초의 시세 지연과 WebSocket 전환이라는 개선 방향을 설계 문서에 적었습니다.' },
      ],
      lessons: [
        '고른 기술만큼 **고르지 않은 기술과 그 이유**(Redis, synchronized, 낙관적 락)를 적어 두니, 설계를 설명할 때 흔들리지 않았습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'e2e-migration',
      featured: true,
      span: 6,
      visual: 'migration',
      title: 'E2E 테스트 Playwright 이관',
      category: 'QA Automation',
      org: '똑똑 현장실습',
      period: '2026.07 – 09',
      role: 'TA · 이관 주도',
      team: 'TA',
      stack: ['Playwright', 'TypeScript', 'Node.js', 'Qase · Slack', 'IMAP'],
      oneLiner: 'Katalon(Groovy) 회귀 테스트를 Playwright(TypeScript)로 옮겨 실행 시간을 70% 줄이고 라이선스 비용을 연 2,000달러 아꼈습니다.',
      summary: '470개 파일, 28,695줄의 Katalon 스크립트를 **먼저 숫자로 분석하고, PoC로 검증한 뒤 단계적으로** Playwright로 옮겼습니다.',
      metrics: [
        { value: '70', unit: '%', label: '회귀 테스트 실행 시간 단축' },
        { prefix: '$', value: '2,000', unit: '/ 년', label: '실행 라이선스 비용 절감' },
        { value: '91.4', unit: '%', label: '사전 분석 — 호출 중 자체 커스텀 키워드 비중' },
        { value: '28,695', unit: '줄', label: '분석한 Katalon 스크립트 (470개 파일)' },
      ],
      overview: [
        '사내 제품의 E2E 회귀 테스트는 Katalon Studio(Groovy)로 돌고 있었고, 일일 구동 시간이 6시간을 넘었으며 실행 라이선스 비용도 들었습니다.',
        '저는 전환 가능성을 먼저 분석한 뒤, PoC 검증을 거쳐 키워드와 핵심 시나리오를 Playwright로 옮기고 병렬 실행과 검증 인프라를 붙였습니다. 이관 기간 Playwright 디렉터리에 가장 많은 커밋을 남겼습니다.',
      ],
      problem: [
        '일일 테스트 구동 시간이 **6시간 2분**까지 늘었습니다.',
        'Katalon 실행 **라이선스 비용**이 계속 발생했습니다.',
        '스크립트 470개 파일 · 28,695줄에서 **호출의 91.4%가 자체 커스텀 키워드**였습니다. 도구를 바꾸려면 이 키워드부터 옮겨야 했습니다.',
      ],
      decisions: [
        {
          title: '전환 전에 호출을 전수로 셌습니다',
          body: '커스텀 키워드 91.4%(13,758회), Katalon 내장 WebUI 8.6%(1,293회), Object Repository 367개 중 실제 사용 317회, 웹서비스 호출 0회를 확인했습니다. 이 결과로 옮겨야 할 대상과 범위를 정하고 PoC로 실제 이관 비용을 검증했습니다.',
        },
        {
          title: 'PoC 뒤 단계적으로 옮겼습니다',
          body: '8월 10일 PoC 검증을 거쳐, 11일부터 14일까지 키워드와 코어 · 비코어 스크립트를 순서대로 이관했습니다.',
        },
        {
          title: '레인을 병렬로 돌렸습니다',
          body: '환경 변수를 분리하고 LIVE · STG · STG_LP 레인을 병렬 실행했습니다. 병렬로 돌 때 다운로드 경로가 부딪히지 않도록 레인별로 나눴습니다.',
          why: '→ 실행 시간 단축의 핵심이었습니다.',
        },
        {
          title: '검증 범위를 넓혔습니다',
          body: '첨부파일 검증과 Qase 연동, IMAP으로 실제 발송 메일을 확인하는 테스트, 만료 토큰 자동 갱신을 추가했습니다. 실패한 테스트만 trace와 영상을 남깁니다.',
        },
      ],
      flow: [
        { k: '01', b: '환경 동기화', s: '프로필 → 환경별 env' },
        { k: '02', b: '레인 실행', s: 'LIVE · STG · STG_LP 병렬', key: true },
        { k: '03', b: 'fixture · 헬퍼', s: '커스텀 키워드 이식본' },
        { k: '04', b: '실패 보존', s: '실패 시에만 trace · video' },
        { k: '05', b: '리포트', s: 'Qase · Slack · 대시보드' },
      ],
      results: [
        { b: '실행 시간 70% 단축', t: '병렬 레인과 Playwright 전환으로 회귀 테스트 구동 시간을 줄였습니다.' },
        { b: '라이선스 연 $2,000 절감', t: 'Katalon 실행 라이선스가 더 이상 필요 없어졌습니다.' },
        { b: '인수인계까지 마무리', t: '레거시 문서를 정리하고 인수인계 문서를 남긴 뒤 다음 업무로 옮겼습니다.' },
      ],
      note: '사내 코드와 환경 정보는 공개하지 않습니다.',
      lessons: [
        '도구 전환을 감이 아니라 **호출 수 전수 집계**에서 시작한 것이 이관 범위를 정하는 기준이 됐습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'utils-server',
      featured: true,
      span: 6,
      visual: 'hub',
      title: '사내 공용 유틸 서버',
      category: 'Backend · Architecture',
      org: '똑똑 현장실습',
      period: '2026.09',
      role: '설계 · 구현 · 제품 연동',
      team: '시장개발TFT',
      stack: ['Node 24 · TypeScript', 'Fastify 5 · TypeBox', 'SQLite', 'Playwright · ffmpeg', 'Docker'],
      oneLiner: '여러 제품 백엔드가 API 키로 호출하는 비동기 작업 서버를 설계하고 제품에 연동했습니다. 첫 유틸은 문서를 설명 영상으로 만드는 파이프라인입니다.',
      summary: '최대 50분이 걸리는 작업을 요청에 붙잡아 두던 구조를, **접수(202) → 작업 폴더 → 폴링 · 서명 웹훅**으로 이어지는 비동기 계약으로 바꿨습니다.',
      metrics: [
        { from: '요청 30분 대기', value: '202', unit: 'Accepted', label: '접수 즉시 작업 id 반환', count: false },
        { from: '7개', value: '3', unit: '개', label: '통합 후 컨테이너 묶음' },
        { value: '128', unit: '개', label: '테스트 (가짜 유틸 · 골든 · 서명 명세 대조)' },
        { value: '749', unit: '줄', label: '설계 문서 v0.8 (13절 · 결정 15건)' },
      ],
      overview: [
        '문서를 설명 영상으로 만드는 기존 파이프라인은 한 번에 한 편만 돌린다는 전제로 짜여 있었습니다. 영상 한 편은 최대 50분이 걸리는데, 제품 백엔드에는 비동기 체계가 없어 긴 요청을 최대 30분까지 붙잡는 방식이었습니다.',
        '이 파이프라인을 여러 제품이 함께 쓰는 서버로 옮기면서, 다른 언어로 된 유틸도 붙일 수 있도록 작업 계약부터 정했습니다. 설계와 구현을 마친 뒤 제품 저장소에 이력째 들여 제품 백엔드와 연동했습니다.',
      ],
      problem: [
        '편끼리 작업 공간을 나눠 쓰고 꼬리표로만 구분해, **꼬리표를 빠뜨리면 앞 편 화면에 뒤 편 나레이션이 얹힌 영상이 오류 없이** 만들어졌습니다. 두 편을 동시에 돌리면 서로의 스토리보드를 집는 구조이기도 했습니다.',
        '서버를 재시작하면 **진행 중인 작업이 함께 죽었습니다.**',
        '제품 백엔드가 **요청을 최대 30분** 붙잡고 있었습니다.',
      ],
      decisions: [
        {
          title: '역할끼리는 DB와 작업 폴더만 봅니다',
          body: 'api · worker · 웹훅 전달 · 청소 역할은 서로 직접 부르지 않고 SQLite와 작업 폴더만 봅니다. worker는 대기 작업 하나를 `UPDATE … RETURNING` 한 문장으로 집고 lease를 갱신해, 같은 작업을 두 번 잡거나 늦게 살아난 워커가 판정을 덮지 못하게 했습니다.',
        },
        {
          title: '작업 폴더를 유일한 경계로 정했습니다',
          body: '`/data/jobs/<id>/` 아래 input · progress · result · log · work · out을 계약으로 삼았습니다. 작업마다 폴더가 분리되니 섞일 수 없고, 이 계약만 지키면 어떤 언어로 만든 유틸도 붙습니다.',
          why: '→ 섞인 영상 문제를 주의가 아니라 구조로 없앴습니다.',
        },
        {
          title: '접수는 202, 기준은 폴링, 웹훅은 알림입니다',
          body: '접수하면 `202`와 작업 id를 돌려주고, 끝나면 Standard Webhooks 형식으로 서명한 웹훅을 보냅니다. 멱등 키는 필수입니다. 웹훅은 알림일 뿐 기준은 폴링이라, 제품 백엔드는 폴링으로 연동했습니다.',
        },
        {
          title: '성공의 정의를 좁혔습니다',
          body: '성공은 “종료 코드 0 **그리고** result.json”입니다. 중간에 끊긴 ffmpeg이 재생 정보 없는 524KB mp4를 남긴 실측이 근거입니다.',
        },
        {
          title: '작업 종류마다 워커를 따로 둡니다',
          body: '워커 하나가 두 종류를 맡으면 영상을 만드는 동안 구성안 요청이 기다린다는 것을 대조 테스트로 재현하고, 풀마다 워커를 나눴습니다. 영상을 렌더하는 중에 요청한 구성안이 24초 만에 나왔습니다. 대신 서버를 재시작하면 돌던 영상은 끊기고 멈춘 단계부터 이어 만든다는 대가를 설계 문서에 적었습니다.',
        },
        {
          title: '옮긴 엔진은 기존 결과와 대조했습니다',
          body: '기존 파이프라인의 스토리보드를 그대로 넣어 비교했습니다. 최종 길이 1:03.40과 라우드니스 -18.4 LUFS가 같았고, 영상 SSIM은 0.9982였습니다.',
        },
        {
          title: '권한은 최소로 받습니다',
          body: '서비스별 API 키만 받고 DB에는 해시만 저장합니다. 제품의 JWT 서명키는 이 서버가 갖지 않고, 브라우저는 이 서버를 직접 부르지 않습니다.',
        },
      ],
      flow: [
        { k: '01', b: '제품 백엔드', s: '서비스 키 · 멱등 키로 요청' },
        { k: '02', b: 'api', s: 'queued 기록 → 202' },
        { k: '03', b: 'worker', s: '풀별로 하나 집기 · lease', key: true },
        { k: '04', b: '유틸 실행', s: '자식 프로세스 · 작업 폴더' },
        { k: '05', b: 'result.json', s: '종료 코드 0 + 결과 파일' },
        { k: '06', b: '폴링 · 웹훅 알림', s: '호출자가 out/ 산출물 수신' },
      ],
      results: [
        { b: '섞인 영상이 구조적으로 불가능', t: '작업마다 폴더를 분리해 꼬리표를 빠뜨리거나 동시에 돌려도 산출물이 섞이지 않습니다.' },
        { b: '재시작해도 작업이 사라지지 않음', t: '끊긴 작업은 중단됨 · 이어 만들기 가능으로 남고, 멈춘 단계부터 다시 이어집니다.' },
        { b: '컨테이너 7개 → 3개', t: '제품 저장소에 이력째 들이면서 다섯 역할을 한 컨테이너 · 한 프로세스로 조립했습니다.' },
        { b: '제품 연동', t: '제품 백엔드가 서비스 키와 멱등 키로 서버 간 호출하고, 통합 테스트 14개로 고정했습니다.' },
      ],
      note: '사내 코드라 원문 대신 구조로 정리했습니다.',
      lessons: [
        '잠깐 자고, 실패하고, 도중에 죽고, 쓰다 만 산출물을 남기는 **가짜 유틸로 워커 계약을 먼저 테스트**했고, 테스트를 일부러 망가뜨려 각 테스트가 정확히 제 결함을 잡는지 확인했습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'compliance-reviewer',
      short: '한국·베트남 산업안전 법령에 비춰 사내 안전규정의 위반·누락을 찾는 LLM 검토 서비스',
      visual: 'regulation',
      title: '안전규정 컴플라이언스 리뷰어',
      category: 'LLM · RegTech',
      org: '시노펙스',
      period: '2026.05',
      role: '단독 개발',
      team: '1인',
      stack: ['Python · FastAPI', 'Gemini 2.5 Flash', 'React 19 · TypeScript', 'pdfplumber'],
      oneLiner: '사내 안전관리 규정을 한국·베트남 산업안전 법령에 비추어 위반과 누락을 찾고 수정 권고를 주는 서비스입니다.',
      summary: '두 나라 법령을 사람이 일일이 대조하기 어렵다는 문제에서 출발했습니다. 법령 원문을 조문 단위로 구조화하고, 모델의 판단을 **실제 조문과 평가 수치로 확인할 수 있게** 만들었습니다.',
      metrics: [
        { value: '718', unit: '개', label: '구조화한 한국 · 베트남 법령 조문' },
        { value: '13', unit: '항목', label: '국가별 체크리스트' },
        { value: '1.00', unit: '', label: '위반 사례 재현율 (평가 표본 2건)' },
      ],
      overview: [
        '사용자가 사내 규정 문서(TXT · PDF · DOCX)를 올리고 국가를 고르면, 해당 국가 법령과 체크리스트만 골라 Gemini에 넘기고 위반·누락 항목을 High · Medium · Low로 돌려받습니다.',
        '모델 응답을 그대로 믿지 않도록, 결과에 나온 조항 번호를 실제 조문 원문과 연결하고 전문가 라벨과 비교하는 평가 도구를 함께 만들었습니다.',
      ],
      problem: [
        '사내 규정이 **한국 산업안전보건법(법 · 시행령 · 시행규칙)과 베트남 법령**을 모두 충족하는지 사람이 대조하기 어렵습니다.',
        'LLM이 인용한 조항을 **원문과 대조할 수 없으면** 결과를 업무에 쓸 수 없습니다.',
        '법령명 표기가 제각각이라(Labour와 Labor 등) **자동 채점이 틀어집니다.**',
      ],
      decisions: [
        {
          title: '법령을 조문 단위 데이터로 만들었습니다',
          body: '산업안전보건법 법 · 시행령 · 시행규칙과 베트남 Law on Labor Safety and Hygiene, Decree 39를 파싱해 조문 718개로 구조화했습니다. 국가를 고르면 필요한 법령만 모델에 넘깁니다.',
        },
        {
          title: '모델이 낸 조항에 원문을 다시 붙입니다',
          body: '응답의 조항 번호를 정규화한 뒤 조문 조회표에서 원문을 찾아 결과에 붙입니다. 사용자는 판단 옆에서 근거 조문을 바로 확인합니다.',
        },
        {
          title: '출력 형식을 먼저 고정했습니다',
          body: '`temperature=0.1`과 넉넉한 출력 토큰 한도로 JSON 응답을 안정화하고, 모델은 설정으로 분리해 바꿀 수 있게 했습니다.',
        },
        {
          title: '조항 단위로 평가합니다',
          body: '(국가, 법령, 조항번호) 단위로 전문가 골드 라벨과 비교해 Precision · Recall · F1과 위험도 일치율을 계산합니다. 법과 시행령은 구분하고 표기 차이는 정규화합니다.',
        },
      ],
      flow: [
        { k: '01', b: '문서 업로드', s: 'TXT · PDF · DOCX 텍스트 추출' },
        { k: '02', b: '법령 선택', s: '국가별 법령 · 체크리스트 필터' },
        { k: '03', b: 'Gemini 검토', s: '토큰 추정 → JSON 응답', key: true },
        { k: '04', b: '조문 연결', s: '조항 번호 정규화 · 원문 첨부' },
        { k: '05', b: '결과', s: 'High · Medium · Low, JSON 다운로드' },
      ],
      results: [
        { b: '위반 사례 재현율 1.00', t: '위반이 들어 있는 문서에서 Precision 0.87, F1 0.93을 기록했습니다.' },
        { b: '남은 과제도 수치로', t: '준수 문서에서 오탐 10건이 나와 전체 Precision은 0.52였습니다. 표본이 2건이라 평가셋 확대가 다음 과제입니다.' },
      ],
      note: '법률 자문이 아닌 검토 보조 도구입니다. 고객사 규정 문서는 공개하지 않습니다.',
      lessons: [
        'LLM 결과는 **근거 조문과 평가 수치가 함께 붙어야** 업무에 쓸 수 있다는 것을 확인했습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'ivory',
      short: 'Lambda 클론 FaaS에서 함수 실행 단계를 실시간 여정으로 보여주는 프론트엔드',
      visual: 'pipeline',
      title: 'Ivory — 실행이 보이는 FaaS',
      category: 'Frontend · Realtime',
      org: 'Softbank 해커톤',
      period: '2025.11 – 12',
      role: '프론트엔드 (FE 커밋 73개 중 49개)',
      team: '팀 프로젝트',
      stack: ['React 19 · TypeScript', 'SSE', 'TanStack Query', 'Framer Motion', 'S3 · CloudFront'],
      oneLiner: 'EC2 러너에서 사용자 함수를 실행하는 Lambda 클론에서, 실행 단계를 실시간 “배송 여정”으로 보여주는 프론트엔드를 만들었습니다.',
      summary: 'AWS Lambda는 실행 과정이 보이지 않는다는 문제의식에서 출발했습니다. 상태를 SSE로 받아 **요청 접수 → 코드 가져오기 → 샌드박스 준비 → 실행 → 완료**를 눈으로 따라갈 수 있게 했습니다.',
      metrics: [
        { value: '49', unit: '/ 73', label: '프론트엔드 커밋 중 본인 작성' },
        { value: '2', unit: '초', label: '상태 단계당 최소 표시 시간' },
        { value: '1,000', unit: '줄', label: '로그 뷰어 버퍼 상한' },
      ],
      overview: [
        'EC2 Runner Pool 위에서 사용자 코드를 실행하는 FaaS 플랫폼입니다. 코드를 올리면 백엔드가 S3에 저장하고 러너를 호출하며, 실행 상태와 로그를 SSE로 흘려보냅니다.',
        '저는 프론트엔드를 맡아 실행 스트림 연결, 상태 여정 애니메이션, 러너 지표 게이지, 배포 자동화를 구현했습니다. 백엔드와 러너는 팀원이 담당했습니다.',
      ],
      problem: [
        '러너가 빨라 **상태 이벤트가 연달아 도착하면 단계별 애니메이션이 건너뛰어졌습니다.** 사용자는 결과만 보고 과정은 보지 못했습니다.',
        'SSE 연결이 **저절로 닫히거나 타임아웃**이 났습니다.',
      ],
      decisions: [
        {
          title: '데이터가 아니라 표시를 늦췄습니다',
          body: '실행 건마다 상태 큐를 두고, 들어온 상태를 순서대로 꺼내 단계당 최소 2초씩 보여줍니다. 실제 상태는 그대로 받되 화면만 사람이 따라갈 수 있는 속도로 재생합니다.',
          why: '→ 정확성은 그대로 두고, 어디서 멈췄는지는 보이게 했습니다.',
        },
        {
          title: '스트림 연결과 화면 상태를 나눴습니다',
          body: '`streamService`가 EventSource 연결과 타임아웃을, `useExecutionStream` 훅이 로그 상태를 맡습니다. 로그는 최대 1,000줄만 유지해 긴 실행에서도 화면이 무거워지지 않습니다.',
        },
        {
          title: '배포를 자동화했습니다',
          body: 'GitHub Actions에서 빌드 → S3 sync → CloudFront 캐시 무효화까지 한 번에 돌렸습니다.',
        },
      ],
      flow: [
        { k: '01', b: '코드 에디터', s: '런타임 · 핸들러 · 페이로드' },
        { k: '02', b: '/invocations', s: 'S3 저장 → EC2 러너 호출' },
        { k: '03', b: 'SSE 스트림', s: '상태 · 로그 이벤트' },
        { k: '04', b: '상태 큐', s: '단계당 최소 2초 재생', key: true },
        { k: '05', b: '여정 · 로그 뷰어', s: '애니메이션 · 1,000줄 버퍼' },
      ],
      code: [
        {
          file: 'src/contexts/ExecutionContext.tsx',
          caption: '상태가 한꺼번에 도착해도 큐에서 하나씩 꺼내 2초 간격으로 화면에 반영합니다.',
          snippet: [
            'const processStatusQueue = useCallback((invocationId: string) => {',
            '  const queue = statusQueueRef.current[invocationId];',
            '  if (!queue || queue.length === 0) {',
            '    isProcessingStatusRef.current[invocationId] = false;',
            '    return;',
            '  }',
            '  isProcessingStatusRef.current[invocationId] = true;',
            '',
            '  const nextStatus = queue.shift();',
            '  if (nextStatus) {',
            '    setExecutions(prev => prev.map(ex =>',
            '      ex.id === invocationId ? { ...ex, status: nextStatus } : ex',
            '    ));',
            '    // Wait 2 seconds before processing the next item',
            '    setTimeout(() => processStatusQueue(invocationId), 2000);',
            '  }',
            '}, []);',
            '',
            'const queueStatusUpdate = useCallback((invocationId: string, status: ExecutionStatus) => {',
            '  statusQueueRef.current[invocationId] ??= [];',
            '  statusQueueRef.current[invocationId].push(status);',
            '  if (!isProcessingStatusRef.current[invocationId]) {',
            '    processStatusQueue(invocationId);',
            '  }',
            '}, [processStatusQueue]);',
          ].join('\n'),
        },
      ],
      results: [
        { b: '과정이 보이는 실행', t: '순식간에 지나가던 상태 변화를 단계별 여정으로 확인할 수 있게 됐습니다.' },
        { b: '러너 지표 시각화', t: 'CloudWatch 지표를 받아 러너 CPU와 메모리를 게이지로 보여줍니다.' },
      ],
      links: [{ label: 'GitHub · Ivory-FE', url: 'https://github.com/Softbank-Ivory/Ivory-FE' }],
      lessons: [
        '실시간 UI에서는 **이벤트가 도착하는 속도와 사람이 이해하는 속도가 다르다**는 점을 설계에 넣어야 했습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'd-light',
      short: '액세스 키 없이 사용자 AWS 계정을 연결하는 원클릭 배포 온보딩 화면',
      visual: 'accounts',
      title: 'D-light — 내 AWS 계정에 원클릭 배포',
      category: 'Frontend · Cloud Onboarding',
      org: 'Softbank 해커톤',
      period: '2025.11',
      role: '프론트엔드 (FE 커밋 50개 중 20개)',
      team: '팀 프로젝트',
      stack: ['React 19 · TypeScript', 'React Router 7', 'MSW', 'CloudFormation'],
      oneLiner: '레포를 고르면 사용자 본인의 AWS 계정에 배포하는 서비스에서, 액세스 키 없이 계정을 연결하는 온보딩 화면과 API 연동을 맡았습니다.',
      summary: '사용자에게 AWS 액세스 키를 받지 않는 것이 제품의 전제였습니다. 사용자가 **CloudFormation Quick Create 링크**로 자기 계정에 역할을 만들면 서비스가 그 역할로 배포합니다. 저는 이 흐름의 **프론트엔드 퍼널**을 만들었습니다.',
      metrics: [
        { value: '20', unit: '/ 50', label: '프론트엔드 커밋 중 본인 작성' },
        { value: '900', unit: '초', label: '템플릿 Presigned URL 유효시간 (백엔드)' },
        { value: '9', unit: '일', label: '해커톤 개발 기간' },
      ],
      overview: [
        'Vercel처럼 GitHub 레포를 고르면 배포되지만, 결과물은 서비스가 아니라 **사용자 자신의 AWS 계정**에 올라갑니다.',
        '저는 AWS 연결 · 리전 선택 · 프레임워크 선택 · 역할 연결 페이지와 자동 배포 API 연동, 인증 라우트 보호를 구현했습니다. 온보딩 백엔드는 팀원이 설계했습니다.',
      ],
      problem: [
        '사용자 계정에 배포하려면 권한이 필요하지만, **자격 증명을 넘겨받는 순간 보안 부담**이 서비스로 넘어옵니다.',
        '토큰 발급 → 링크 생성 → 콘솔에서 스택 생성 → 콜백까지 **여러 단계를 사용자가 이탈 없이** 지나가야 합니다.',
      ],
      decisions: [
        {
          title: '역할 연결 페이지에서 요청을 이어 붙였습니다',
          body: '`AWSRoleAssumePage`는 등록 토큰 응답을 받으면 곧바로 Quick Create 링크를 요청합니다. externalId는 프론트에서 만들지 않고 백엔드가 발급한 값을 그대로 씁니다.',
        },
        {
          title: '백엔드를 기다리지 않고 개발했습니다',
          body: 'MSW로 API를 먼저 목킹해 두고 화면을 병렬로 개발했습니다.',
        },
        {
          title: '인증이 필요한 경로를 막았습니다',
          body: '`ProtectedRoute`로 로그인하지 않은 사용자가 배포 단계에 들어오지 못하게 했습니다.',
        },
      ],
      flow: [
        { k: '01', b: '레포 · 프레임워크', s: 'GitHub 레포 선택' },
        { k: '02', b: '리전 선택', s: '배포 대상 리전' },
        { k: '03', b: 'Role Assume', s: '토큰 → Quick Create 링크', key: true },
        { k: '04', b: '사용자 콘솔', s: '스택 생성 → Lambda 콜백' },
        { k: '05', b: '배포', s: '확인 → 배포 → 상태 확인' },
      ],
      results: [
        { b: '키 없는 계정 연결 퍼널', t: '토큰 발급부터 콘솔 스택 생성, 배포 상태 확인까지 이어지는 화면 흐름을 완성했습니다.' },
      ],
      links: [{ label: 'GitHub · D-lite_FE', url: 'https://github.com/Softbank-Hackathon/D-lite_FE' }],
      lessons: [
        '보안 설계가 좋아도 **단계가 많으면 사용자가 떠납니다.** 단계마다 지금 무엇을 기다리는지 보여주는 화면이 중요했습니다.',
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'ai-sentinel',
      short: 'AI 에이전트 행동을 판정하고 해시로 감사하는 게이트웨이 설계와 UI 프로토타입',
      visual: 'orbit',
      title: 'AI Sentinel — 에이전트 감사 게이트웨이',
      category: 'Governance · Prototype',
      org: 'Kopilot 팀 과제',
      period: '2026.04 – 05',
      role: '감사 기록 설계 · UI 프로토타입',
      team: '팀 과제',
      stack: ['Next.js 16', 'React 19 · TypeScript', 'Tailwind 4', 'shadcn/ui'],
      oneLiner: 'AI 에이전트의 행동을 액션 단위로 허용·마스킹·사람 검토·거부하고, 판정을 해시로 남기는 게이트웨이를 설계하고 프로토타입으로 보여줬습니다.',
      summary: '에이전트가 민감정보나 고위험 작업에 접근할 때 **통제와 사후 증명 수단이 없다**는 문제를 다뤘습니다. 정책 판정과 온체인 감사 기록은 **설계**이고, 구현은 이 흐름을 재생하는 UI 프로토타입입니다.',
      metrics: [
        { value: '4', unit: '가지', label: '판정 유형 — ALLOW · MASKED · HUMAN_REVIEW · DENY' },
        { value: '7', unit: '개', label: '시뮬레이터 시나리오' },
        { value: '9', unit: '개', label: 'RBAC · ABAC · AI 정책 예시' },
      ],
      overview: [
        '에이전트 요청을 게이트웨이가 가로채 액션 단위로 나누고, 정책에 따라 네 가지로 판정하는 구조를 설계했습니다. 모든 판정은 해시로 만들어 블록체인에 앵커링하는 것을 전제로 했습니다.',
        '구현은 Next.js 프로토타입으로, 에이전트 · 정책 · 감사 로그 · 시뮬레이터 화면을 mock 데이터로 구성했습니다.',
      ],
      problem: [
        '에이전트가 **개인정보나 고위험 작업**에 접근해도 사전에 통제할 지점이 없습니다.',
        '사고가 난 뒤 **누가 무엇을 허용했는지 증명**하기 어렵습니다.',
      ],
      decisions: [
        {
          title: '판정을 네 갈래로 나눴습니다',
          body: '허용과 거부 외에, 개인정보를 가리고 통과시키는 MASKED와 Slack으로 사람 승인을 받는 HUMAN_REVIEW를 두었습니다.',
        },
        {
          title: '감사 기록은 해시로 앵커링하도록 설계했습니다',
          body: '판정 레코드를 해시로 만들어 온체인에 남기면 기록이 나중에 바뀌지 않았음을 보일 수 있습니다. 감사 화면에는 해시와 앵커 상태를 보여주는 UI를 만들었습니다.',
        },
      ],
      flow: [
        { k: '01', b: '에이전트 요청', s: '프롬프트 · 도구 호출' },
        { k: '02', b: 'Gateway', s: '액션 단위로 분해' },
        { k: '03', b: '정책 평가', s: 'RBAC · ABAC · AI', key: true },
        { k: '04', b: '판정', s: 'ALLOW · MASKED · REVIEW · DENY' },
        { k: '05', b: '감사 앵커링', s: '판정 해시 → 온체인 (설계)' },
      ],
      results: [
        { b: '시뮬레이터로 설계 설명', t: '시나리오 7개의 판정 흐름을 단계별로 재생해 설계를 보여줄 수 있게 했습니다.' },
      ],
      note: '정책 엔진, 게이트웨이, 블록체인 앵커링은 설계 단계이며 코드로 구현하지 않았습니다.',
    },
  ],

  experience: [
    {
      date: '2026.09 — 현재',
      org: '똑똑',
      role: '시장개발TFT · 현장실습',
      desc: 'VC 실무자용 도구 플랫폼에 **제재 명단 스크리닝 기능**(OFAC · UN · 금융위 고시)을 명단 파서부터 검토 화면까지 구현했습니다. 여러 제품이 함께 쓰는 **비동기 유틸 서버**를 설계하고 제품에 연동했습니다.',
    },
    {
      date: '2026.07 — 2026.09',
      org: '똑똑',
      role: 'TA · 현장실습',
      desc: 'Katalon 회귀 테스트를 Playwright로 이관해 **실행 시간 70% 단축**, **라이선스 연 $2,000 절감**.',
    },
    {
      date: '2026.02',
      org: '한화 공모전',
      role: 'Art-ABS 트랜치 RWA 컨트랙트',
      desc: 'ERC-1155 트랜치 토큰, 서명 기반 상태머신, 오라클 합의 워터폴 정산을 Solidity로 구현했습니다.',
      badge: '2라운드 진출',
    },
    {
      date: '2025.11 — 2025.12',
      org: '예강희망키움 PoC 해커톤',
      role: 'Bitable · 백엔드',
      desc: '음성 모의 거래소 백엔드. 시세 조회 **150–300ms → 1ms 미만**, 비관적 락으로 잔고 이중 차감 차단.',
    },
    {
      date: '2025.11 — 2025.12',
      org: 'Softbank 해커톤',
      role: 'D-light · Ivory · 프론트엔드',
      desc: 'CloudFormation 계정 연결 퍼널(D-light)과 SSE 실행 여정 UI(Ivory)를 만들었습니다.',
    },
    {
      date: '2025.02 — 현재',
      org: '시노펙스',
      role: 'AI인공신장사업팀 · 프리랜서',
      desc: '병원 관리자 플랫폼 풀스택 개발과 **MetaMask 서명 로그인**, 한국·베트남 안전규정 검토 서비스를 만들었습니다.',
    },
    {
      date: '2024.12 — 2025.01',
      org: 'KAIST 몰입캠프',
      role: '24W',
      desc: '매주 팀과 스택을 바꿔 프로젝트를 만들었습니다. 러닝 게임 앱의 백엔드(Spring Boot · JWT · 스케줄러)를 맡아 74커밋 중 62개를 작성했습니다.',
    },
  ],

  education: [
    { label: 'Education', title: '고려대학교 컴퓨터학과', sub: '심화전공 · 2020.03 입학 · 2027.02 졸업 예정' },
    { label: 'Certificates', title: 'SQLD · ADsP', sub: '2025.09 취득' },
    { label: 'Language', title: 'OPIc AL · TOEIC 870', sub: '영어' },
  ],
};
